// Words for the diagrams in scripts/diagrams.mjs. Names of files, fields,
// providers and Git refs stay as they are in the code; commands are given in
// the CLI's Russian form for Russian and in its English form elsewhere.
export const T = {
  ru: {
    tagline: 'задачи · доказательства · приёмка · знания',
    bannerDesc: 'Миска борща, над которой поднимается пар и модули-кубики: задачи, проверки и знания собираются в одно пространство.',
    arch: {
      title: 'Как устроен Borshkit', sub: 'Node.js 22+ · ноль зависимостей · всё хранится локально',
      inputs: 'Кто вызывает', you: 'Ты', youL: 'команды в терминале', ccL: 'плагин: хуки, навык',
      agents: 'Codex и другие', agentsL: 'читают AGENTS.md', person: 'Только ты', personL1: 'терминал / passkey', personL2: 'настройки: passkey', personL3: 'Git: терминал',
      core: 'core/ — ядро', g1: 'Пространство', g1d: 'настройки меняются только через предложения',
      g2: 'Задачи и приёмка', g2d: 'доказательства привязаны к состоянию',
      g3: 'Работы', g3d: 'роль + исполнитель, пулы, вопросы, диспетчерская',
      g4: 'Знания и Git', g4d: 'карта проекта, источники, сборка и отправка',
      files: 'Где лежат файлы', spaceL: 'пространство · Obsidian · своя история Git',
      copy: 'Копия задачи', copyL: 'git worktree · ветка borshkit/<id>', project: 'Проект', projectL: 'твои файлы и история Git',
      exec: 'Исполнители: получают пакет задания, отвечают JSON по схеме', api: 'Любой API · Ollama', own: 'Своя программа',
      sub2: 'по подписке', sub3: 'ключ — по имени', sub4: 'читает stdin',
      aPacket: 'пакет задания', aJson: 'ответ JSON',
      aWrite: 'пишут только в копию', aMerge: 'собрать', aPush: 'отправить →',
      caption: 'Решает и записывает ядро; исполнители только предлагают. В проект попадает лишь принятое.',
    },
    flow: {
      title: 'Путь задачи', sub: 'каждый шаг оставляет запись, привязанную к точному состоянию файлов',
      n1: 'Задача', n1c: 'задача новая', n1l: 'цель · критерии · paths',
      n2: 'Анализ', n2c: 'задача анализ', n2l: 'слепая зона заранее',
      n3: 'Работа', n3c: 'работа запустить', n3l: 'implementer в копии',
      n4a: 'Проверки (auto)', n4ac: 'задача проверить', n4al: 'в копии → лог + sha256',
      n4b: 'Ревью (model)', n4bc: '--роль reviewer', n4bl: 'другая семья моделей',
      n5: 'Итог', n5c: 'задача итог', n5l1: 'сверка', n5l2: 'состояния',
      lConverge: 'один из итогов',
      o1: 'нужно исправить', o1l1: 'FAIL проверки или ревью', o1l2: 'или правки вне paths',
      o2: 'не проверено', o2l1: 'нет доказательства', o2l2: 'или оно устарело',
      o3: 'ждёт тебя', o3l1: 'ручной критерий или PASS', o3l2: 'модели без цели доверия',
      o4: 'принято', o4l1: 'все цели достигнуты', o4l2: 'на этом состоянии',
      lFix: 'исправить', lRecheck: 'проверить заново', lAnswer: 'итог заново',
      you: 'Ты', youc: 'задача подтвердить', youl: 'шаги из листа приёмки',
      m: 'Собрать', mc: 'собрать', ml1: 'копия чистая', ml2: 'и содержит', ml3: 'текущий main',
      p: 'Отправить', pc: 'отправить', pl1: 'ключи во всём,', pl2: 'чего нет', pl3: 'на remote',
      up: 'Обновить задачу', upc: 'задача обновить', upl: 'main → в копию, проверки заново', lMoved: 'main ушёл вперёд',
      caption: '«Готово» от модели — не приёмка: решают проверки, ревью другой семьи моделей и ты.',
    },
    ev: {
      title: 'Доказательство привязано к состоянию', sub: 'состояние — пять отпечатков; совпали все — запись действует',
      state: 'Состояние (снимок)', r1: 'Файлы проекта', r1l: 'HEAD + sha256 файлов, бит x, подмодули',
      r2: 'Контракт', r2l: 'sha256(contract.json)', r3: 'Настройки', r3l: 'sha256(settings/workspace.json)',
      r4: 'Материалы', r4l: 'sha256 копий источников задачи', r5: 'Код Borshkit', r5l: 'sha256(core/*.mjs, bin/*.mjs)',
      src: 'Откуда берутся записи', k1: 'Проверка (auto)', k1c: 'задача проверить', k1l: 'снимок до и после проверки',
      k2: 'Ревью (model)', k2c: 'работа … reviewer', k2l: 'снимок на старте ревьюера',
      k3: 'Ты (manual)', k3c: 'задача подтвердить', k3l: 'снимок в момент ответа',
      rec: 'Запись', recl: 'лог проверки защищён своим sha256',
      cmp: 'Сверка', cmpc: 'задача итог', cmpq: 'снимок сейчас = state записи?', cmpl1: 'да → запись действует', cmpl2: 'нет → устарела, не засчитана',
      time: 'Как это выглядит во времени',
      lane1: 'Проверка', e1: 'PASS', e2: 'правка файла', e3: 'запись устарела', e4: 'новая проверка: PASS',
      lane2: 'Ревью', f1: 'ревьюер начал', f2: 'файл изменился', f3: 'ответ пришёл — ревью сразу устарело',
      caption: 'Изменился хоть байт, контракт, настройки или сам Borshkit — запись больше не засчитывается.',
    },
    pool: {
      title: 'Как работа находит исполнителя', sub: 'кандидаты из пула по порядку; каждый проходит четыре фильтра',
      job: 'Работа', jobc: 'работа запустить', jobl: 'пул — упорядоченный список',
      cand: 'Кандидаты', gates: 'Фильтры · нет → следующий',
      g1: 'Приватность разрешает', g1l: 'строгий режим: только local / no-train',
      g2: 'Умеет нужное', g2l: 'выходы роли, схема ответа, probe',
      g3: 'Не та же семья, что автор', g3l: 'для ревью; авторы — из authors.json',
      g4: 'В пакете нет ключей и ПД', g4l: 'нашлись → стоп всей работы',
      run: 'Запуск',
      runl1: 'окружение: только разрешённые переменные',
      runl2: 'пишущие роли — в копии задачи, одна за раз',
      runl3: 'в пакете: роль, навыки, контракт, проверки',
      ok: 'ответ по схеме', okl1: 'и код 0: ревью → evidence,', okl2: 'файлы → коммит в копии',
      next: 'лимит', nextl1: 'к следующему;', nextl2: 'правки — свой коммит',
      fail: 'другая ошибка', faill1: 'работа FAILED;', faill2: 'ответ сохранён для тебя',
      ask: 'тишина > 60 с', askl1: 'вопрос; автопилот', askl2: 'ждёт или передаёт',
      toNext: 'следующий кандидат', exhausted: 'кандидаты кончились',
      stopT: 'Критическая остановка', stop: 'Пул исчерпан', stopl: 'решает только человек',
      stopf: 'точка возврата + контекст для следующего', you: 'Ты', youc1: 'вопрос ответить <номер> wait', youc2: 'работа продолжить <работа>',
      board: 'диспетчерская', s: ['claude: лимит исчерпан → codex', 'codex: работает…', 'codex: готово ✓ · переключений: 1'],
      caption: 'Каждая передача видна в STATUS.md и в строке статуса; решение за человеком — только при остановке.',
    },
    kb: {
      title: 'Знания: заметки → граф и SQL → контекст', sub: 'источник правды — заметки; SQL — производная, её можно пересобрать',
      srcT: 'Источники', s1: 'Код JS/TS', s1l: '→ imports, tests (+ обратные)',
      s2: 'Markdown проекта', s2l: '→ documents, references',
      s3: 'Frontmatter Borshkit', s3l: '→ типизированные связи, DECLARED',
      s4: 'Твои заметки', s4l: 'Borshkit их читает, но не меняет',
      s5: 'Принятые задачи и уроки', s5l: 'урок устаревает вместе со своим кодом',
      build: 'Сборка', buildc: 'знания собрать', buildl: 'то же состояние → те же строки',
      genl1: 'заметки о коде и документах', genl2: 'перезаписываются целиком',
      sqll: 'пересобирается из заметок',
      useT: 'Кто пользуется', u1: 'Obsidian', u1c: 'borshkit/ как хранилище', u1l: 'граф из [[связей]]',
      u2: 'Запросы', u2c: 'знания sql "SELECT …"', u2l: 'только SELECT / WITH, база только для чтения',
      u3: 'Контекст работы', u3c: 'знания контекст <задача>', u3l: 'срез по paths задачи ≤ 8000 знаков в пакет',
      u4: 'Выгрузка', u4c: 'знания экспорт [--sql]', u4l: 'ссылки для GitHub или SQL-скрипт',
      example: 'Пример: стрелка идёт от заметки, в которой записана связь',
      caption: 'Карта понимает JS/TS и Markdown; Swift, Python и Go пока не разбираются. На приёмку карта не влияет.',
    },
  },
  en: {
    tagline: 'tasks · evidence · acceptance · knowledge',
    bannerDesc: 'A bowl of borscht with steam and module cubes rising above it: tasks, checks and knowledge come together in one workspace.',
    arch: {
      title: 'How Borshkit is built', sub: 'Node.js 22+ · zero dependencies · everything is stored locally',
      inputs: 'Who calls it', you: 'You', youL: 'commands in a terminal', ccL: 'plugin: hooks, skill',
      agents: 'Codex and others', agentsL: 'read AGENTS.md', person: 'Only you', personL1: 'terminal / passkey', personL2: 'settings: passkey', personL3: 'Git: terminal',
      core: 'core/ — the core', g1: 'Workspace', g1d: 'settings change only through proposals',
      g2: 'Tasks and acceptance', g2d: 'evidence is bound to the state',
      g3: 'Jobs', g3d: 'role + executor, pools, questions, dispatcher',
      g4: 'Knowledge and Git', g4d: 'project map, sources, merge and push',
      files: 'Where files live', spaceL: 'workspace · Obsidian vault · own Git history',
      copy: 'Task copy', copyL: 'git worktree · branch borshkit/<id>', project: 'Project', projectL: 'your files and Git history',
      exec: 'Executors: get a task packet, answer JSON by schema', api: 'Any API · Ollama', own: 'Your own program',
      sub2: 'on subscription', sub3: 'key by name only', sub4: 'reads stdin',
      aPacket: 'task packet', aJson: 'JSON answer',
      aWrite: 'write only to the copy', aMerge: 'merge', aPush: 'push →',
      caption: 'The core decides and records; executors only propose. Only accepted work reaches the project.',
    },
    flow: {
      title: 'The path of a task', sub: 'every step leaves a record bound to the exact state of the files',
      n1: 'Task', n1c: 'task new', n1l: 'goal · criteria · paths',
      n2: 'Analysis', n2c: 'task check', n2l: 'blind spots up front',
      n3: 'Work', n3c: 'job run', n3l: 'implementer in the copy',
      n4a: 'Checks (auto)', n4ac: 'task verify', n4al: 'in the copy → log + sha256',
      n4b: 'Review (model)', n4bc: '--role reviewer', n4bl: 'a different model family',
      n5: 'Verdict', n5c: 'task converge', n5l1: 'states', n5l2: 'compared',
      lConverge: 'one of the outcomes',
      o1: 'needs a fix', o1l1: 'FAIL from a check or review', o1l2: 'or edits outside paths',
      o2: 'not checked', o2l1: 'no evidence', o2l2: 'or it went stale',
      o3: 'waits for you', o3l1: 'a manual criterion, or a', o3l2: 'model PASS without trust',
      o4: 'accepted', o4l1: 'every goal reached', o4l2: 'on this state',
      lFix: 'fix', lRecheck: 'check again', lAnswer: 'verdict again',
      you: 'You', youc: 'task confirm', youl: 'steps from the acceptance sheet',
      m: 'Merge', mc: 'merge', ml1: 'copy is clean', ml2: 'and contains', ml3: 'current main',
      p: 'Push', pc: 'push', pl1: 'keys in all', pl2: 'that is new', pl3: 'to the remote',
      up: 'Update the task', upc: 'task update', upl: 'main → into the copy, check again', lMoved: 'main moved on',
      caption: 'A model saying “done” is not acceptance: checks, a review by another model family and you decide.',
    },
    ev: {
      title: 'Evidence is bound to a state', sub: 'a state is five fingerprints; when all match, the record counts',
      state: 'State (snapshot)', r1: 'Project files', r1l: 'HEAD + sha256 of files, x bit, submodules',
      r2: 'Contract', r2l: 'sha256(contract.json)', r3: 'Settings', r3l: 'sha256(settings/workspace.json)',
      r4: 'Materials', r4l: 'sha256 of the task’s stored sources', r5: 'Borshkit code', r5l: 'sha256(core/*.mjs, bin/*.mjs)',
      src: 'Where records come from', k1: 'Check (auto)', k1c: 'task verify', k1l: 'snapshot before and after the check',
      k2: 'Review (model)', k2c: 'job run … reviewer', k2l: 'snapshot when the reviewer started',
      k3: 'You (manual)', k3c: 'task confirm', k3l: 'snapshot at your answer',
      rec: 'Record', recl: 'the check log is protected by its own sha256',
      cmp: 'Comparison', cmpc: 'task converge', cmpq: 'snapshot now = record state?', cmpl1: 'yes → the record counts', cmpl2: 'no → stale, not counted',
      time: 'What it looks like over time',
      lane1: 'Check', e1: 'PASS', e2: 'a file is edited', e3: 'the record is stale', e4: 'new check: PASS',
      lane2: 'Review', f1: 'reviewer starts', f2: 'a file changes', f3: 'the answer arrives — stale at once',
      caption: 'Change one byte, the contract, the settings or Borshkit itself, and the record no longer counts.',
    },
    pool: {
      title: 'How a job finds an executor', sub: 'pool candidates in order; each must pass four filters',
      job: 'Job', jobc: 'job run', jobl: 'a pool is an ordered list',
      cand: 'Candidates', gates: 'Filters · no → next one',
      g1: 'Privacy mode allows it', g1l: 'strict mode: only local / no-train',
      g2: 'Can do what is needed', g2l: 'role outputs, answer schema, probe',
      g3: 'Not the author’s family', g3l: 'for reviews; authors from authors.json',
      g4: 'No keys or personal data', g4l: 'found → the whole job stops',
      run: 'Run',
      runl1: 'environment: allowed variables only',
      runl2: 'writers work in the task copy, one at a time',
      runl3: 'packet: role, skills, contract, checks',
      ok: 'schema answer', okl1: 'exit 0: review → evidence,', okl2: 'files → commit in copy',
      next: 'limit', nextl1: 'to the next one;', nextl2: 'edits get a commit',
      fail: 'another error', faill1: 'job FAILED;', faill2: 'the answer is kept for you',
      ask: 'silent > 60 s', askl1: 'a question; autopilot', askl2: 'waits or hands over',
      toNext: 'next candidate', exhausted: 'no candidates left',
      stopT: 'Critical stop', stop: 'Pool exhausted', stopl: 'only a person decides',
      stopf: 'restore point + context for the next one', you: 'You', youc1: 'question answer <id> wait', youc2: 'job resume <job>',
      board: 'dispatcher', s: ['claude: limit reached → codex', 'codex: working…', 'codex: done ✓ · switches: 1'],
      caption: 'Every hand-over shows in STATUS.md and the status line; a person decides only at a stop.',
    },
    kb: {
      title: 'Knowledge: notes → graph and SQL → context', sub: 'notes are the source of truth; SQL is derived and can be rebuilt',
      srcT: 'Sources', s1: 'JS/TS code', s1l: '→ imports, tests (+ reverse links)',
      s2: 'Project Markdown', s2l: '→ documents, references',
      s3: 'Borshkit frontmatter', s3l: '→ typed links, DECLARED',
      s4: 'Your notes', s4l: 'Borshkit reads them, never changes them',
      s5: 'Accepted tasks and lessons', s5l: 'a lesson goes stale with its code',
      build: 'Build', buildc: 'knowledge build', buildl: 'same state → same rows',
      genl1: 'notes on code and documents', genl2: 'rewritten as a whole',
      sqll: 'rebuilt from the notes',
      useT: 'Who uses it', u1: 'Obsidian', u1c: 'borshkit/ as a vault', u1l: 'graph from [[links]]',
      u2: 'Queries', u2c: 'knowledge sql "SELECT …"', u2l: 'SELECT / WITH only, read-only database',
      u3: 'Job context', u3c: 'knowledge context <task>', u3l: 'slice by the task’s paths, ≤ 8000 chars',
      u4: 'Export', u4c: 'knowledge export [--sql]', u4l: 'links for GitHub or a SQL script',
      example: 'Example: an arrow starts at the note that holds the link',
      caption: 'The map reads JS/TS and Markdown; Swift, Python and Go are not parsed yet. Acceptance does not use the map.',
    },
  },
  de: {
    tagline: 'Aufgaben · Nachweise · Abnahme · Wissen',
    bannerDesc: 'Eine Schüssel Borschtsch, über der Dampf und Modulwürfel aufsteigen: Aufgaben, Prüfungen und Wissen kommen in einem Arbeitsbereich zusammen.',
    arch: {
      title: 'Wie Borshkit aufgebaut ist', sub: 'Node.js 22+ · keine Abhängigkeiten · alles bleibt lokal',
      inputs: 'Wer es aufruft', you: 'Du', youL: 'Befehle im Terminal', ccL: 'Plugin: Hooks, Skill',
      agents: 'Codex und andere', agentsL: 'lesen AGENTS.md', person: 'Nur du', personL1: 'Terminal / Passkey', personL2: 'Einstellungen: Passkey', personL3: 'Git: Terminal',
      core: 'core/ — der Kern', g1: 'Arbeitsbereich', g1d: 'Einstellungen ändern sich nur über Vorschläge',
      g2: 'Aufgaben und Abnahme', g2d: 'Nachweise sind an den Zustand gebunden',
      g3: 'Aufträge', g3d: 'Rolle + Ausführer, Pools, Fragen, Leitstand',
      g4: 'Wissen und Git', g4d: 'Projektkarte, Quellen, Mergen und Pushen',
      files: 'Wo die Dateien liegen', spaceL: 'Arbeitsbereich · Obsidian · eigene Git-Historie',
      copy: 'Aufgabenkopie', copyL: 'git worktree · Branch borshkit/<id>', project: 'Projekt', projectL: 'deine Dateien und Git-Historie',
      exec: 'Ausführer: bekommen ein Aufgabenpaket, antworten JSON nach Schema', api: 'Jede API · Ollama', own: 'Eigenes Programm',
      sub2: 'per Abo', sub3: 'Schlüssel nur per Name', sub4: 'liest stdin',
      aPacket: 'Aufgabenpaket', aJson: 'JSON-Antwort', aWrite: 'schreiben nur in die Kopie', aMerge: 'mergen', aPush: 'pushen →',
      caption: 'Der Kern entscheidet und protokolliert; Ausführer schlagen nur vor. Ins Projekt kommt nur Abgenommenes.',
    },
    flow: {
      title: 'Der Weg einer Aufgabe', sub: 'jeder Schritt hinterlässt einen Eintrag, gebunden an den genauen Dateizustand',
      n1: 'Aufgabe', n1c: 'task new', n1l: 'Ziel · Kriterien · paths',
      n2: 'Analyse', n2c: 'task check', n2l: 'blinde Flecken vorab',
      n3: 'Arbeit', n3c: 'job run', n3l: 'implementer in der Kopie',
      n4a: 'Prüfungen (auto)', n4ac: 'task verify', n4al: 'in der Kopie → Log + sha256',
      n4b: 'Review (model)', n4bc: '--role reviewer', n4bl: 'andere Modellfamilie',
      n5: 'Ergebnis', n5c: 'task converge', n5l1: 'Zustände', n5l2: 'abgeglichen',
      lConverge: 'eines der Ergebnisse',
      o1: 'muss korrigiert werden', o1l1: 'FAIL einer Prüfung/Review', o1l2: 'oder Änderung außerhalb paths',
      o2: 'nicht geprüft', o2l1: 'kein Nachweis', o2l2: 'oder er ist veraltet',
      o3: 'wartet auf dich', o3l1: 'manuelles Kriterium oder', o3l2: 'Modell-PASS ohne Vertrauen',
      o4: 'abgenommen', o4l1: 'alle Ziele erreicht', o4l2: 'in diesem Zustand',
      lFix: 'korrigieren', lRecheck: 'neu prüfen', lAnswer: 'Ergebnis neu',
      you: 'Du', youc: 'task confirm', youl: 'Schritte aus dem Abnahmeblatt',
      m: 'Mergen', mc: 'merge', ml1: 'Kopie sauber', ml2: 'und enthält', ml3: 'aktuelles main',
      p: 'Pushen', pc: 'push', pl1: 'Schlüssel in', pl2: 'allem Neuen', pl3: 'für das Remote',
      up: 'Aufgabe aktualisieren', upc: 'task update', upl: 'main → in die Kopie, neu prüfen', lMoved: 'main ist weiter',
      caption: '„Fertig“ vom Modell ist keine Abnahme: Es entscheiden Prüfungen, ein Review einer anderen Modellfamilie und du.',
    },
    ev: {
      title: 'Ein Nachweis gehört zu einem Zustand', sub: 'ein Zustand sind fünf Fingerabdrücke; stimmen alle, zählt der Eintrag',
      state: 'Zustand (Snapshot)', r1: 'Projektdateien', r1l: 'HEAD + sha256 der Dateien, x-Bit, Submodule',
      r2: 'Vertrag', r2l: 'sha256(contract.json)', r3: 'Einstellungen', r3l: 'sha256(settings/workspace.json)',
      r4: 'Materialien', r4l: 'sha256 der gespeicherten Quellen', r5: 'Borshkit-Code', r5l: 'sha256(core/*.mjs, bin/*.mjs)',
      src: 'Woher Einträge kommen', k1: 'Prüfung (auto)', k1c: 'task verify', k1l: 'Snapshot vor und nach der Prüfung',
      k2: 'Review (model)', k2c: 'job run … reviewer', k2l: 'Snapshot beim Start des Reviewers',
      k3: 'Du (manual)', k3c: 'task confirm', k3l: 'Snapshot bei deiner Antwort',
      rec: 'Eintrag', recl: 'das Prüf-Log ist per sha256 geschützt',
      cmp: 'Abgleich', cmpc: 'task converge', cmpq: 'Snapshot jetzt = Zustand im Eintrag?', cmpl1: 'ja → der Eintrag zählt', cmpl2: 'nein → veraltet, zählt nicht',
      time: 'So sieht es über die Zeit aus',
      lane1: 'Prüfung', e1: 'PASS', e2: 'Datei geändert', e3: 'Eintrag veraltet', e4: 'neue Prüfung: PASS',
      lane2: 'Review', f1: 'Reviewer startet', f2: 'Datei ändert sich', f3: 'Antwort kommt — sofort veraltet',
      caption: 'Ändert sich ein Byte, der Vertrag, die Einstellungen oder Borshkit selbst, zählt der Eintrag nicht mehr.',
    },
    pool: {
      title: 'Wie ein Auftrag seinen Ausführer findet', sub: 'Kandidaten aus dem Pool der Reihe nach; jeder durchläuft vier Filter',
      job: 'Auftrag', jobc: 'job run', jobl: 'Pool = geordnete Liste',
      cand: 'Kandidaten', gates: 'Filter · nein → nächster',
      g1: 'Datenschutz erlaubt es', g1l: 'strikt: nur local / no-train',
      g2: 'Kann, was nötig ist', g2l: 'Rollenausgaben, Schema, Probe',
      g3: 'Nicht die Familie des Autors', g3l: 'für Reviews; Autoren aus authors.json',
      g4: 'Keine Schlüssel und PII', g4l: 'gefunden → ganzer Auftrag stoppt',
      run: 'Start',
      runl1: 'Umgebung: nur erlaubte Variablen',
      runl2: 'Schreiber arbeiten in der Kopie, einer nach dem anderen',
      runl3: 'Paket: Rolle, Skills, Vertrag, Prüfungen',
      ok: 'Schema-Antwort', okl1: 'Code 0: Review → evidence,', okl2: 'Dateien → Commit in Kopie',
      next: 'Limit', nextl1: 'zum Nächsten;', nextl2: 'Änderung: Commit',
      fail: 'anderer Fehler', faill1: 'Auftrag FAILED;', faill2: 'Antwort bleibt für dich',
      ask: 'still > 60 s', askl1: 'Frage; Autopilot', askl2: 'wartet oder gibt ab',
      toNext: 'nächster Kandidat', exhausted: 'keine Kandidaten mehr',
      stopT: 'Kritischer Stopp', stop: 'Pool erschöpft', stopl: 'nur ein Mensch entscheidet',
      stopf: 'Wiederherstellungspunkt + Kontext', you: 'Du', youc1: 'question answer <id> wait', youc2: 'job resume <job>',
      board: 'Leitstand', s: ['claude: Limit erreicht → codex', 'codex: arbeitet…', 'codex: fertig ✓ · Wechsel: 1'],
      caption: 'Jede Übergabe steht in STATUS.md und in der Statuszeile; ein Mensch entscheidet nur beim Stopp.',
    },
    kb: {
      title: 'Wissen: Notizen → Graph und SQL → Kontext', sub: 'Notizen sind die Quelle der Wahrheit; SQL ist abgeleitet und neu baubar',
      srcT: 'Quellen', s1: 'JS/TS-Code', s1l: '→ imports, tests (+ Rückrichtung)',
      s2: 'Markdown im Projekt', s2l: '→ documents, references',
      s3: 'Borshkit-Frontmatter', s3l: '→ typisierte Links, DECLARED',
      s4: 'Deine Notizen', s4l: 'Borshkit liest sie, ändert sie nie',
      s5: 'Aufgaben und Lektionen', s5l: 'Lektion veraltet mit ihrem Code',
      build: 'Aufbau', buildc: 'knowledge build', buildl: 'gleicher Zustand → gleiche Zeilen',
      genl1: 'Notizen zu Code und Dokumenten', genl2: 'werden ganz neu geschrieben',
      sqll: 'aus den Notizen neu gebaut',
      useT: 'Wer es nutzt', u1: 'Obsidian', u1c: 'borshkit/ als Vault', u1l: 'Graph aus [[Links]]',
      u2: 'Abfragen', u2c: 'knowledge sql "SELECT …"', u2l: 'nur SELECT / WITH, Datenbank nur lesend',
      u3: 'Kontext eines Auftrags', u3c: 'knowledge context <task>', u3l: 'Ausschnitt nach paths, ≤ 8000 Zeichen',
      u4: 'Export', u4c: 'knowledge export [--sql]', u4l: 'Links für GitHub oder ein SQL-Skript',
      example: 'Beispiel: Ein Pfeil beginnt bei der Notiz, die den Link enthält',
      caption: 'Die Karte liest JS/TS und Markdown; Swift, Python und Go noch nicht. Die Abnahme nutzt die Karte nicht.',
    },
  },
  ko: {
    tagline: '작업 · 증거 · 인수 · 지식',
    bannerDesc: '김과 모듈 큐브가 피어오르는 보르시 한 그릇: 작업, 검사, 지식이 하나의 작업 공간에 모입니다.',
    arch: {
      title: 'Borshkit의 구조', sub: 'Node.js 22+ · 의존성 없음 · 모든 것은 로컬에 저장',
      inputs: '호출하는 쪽', you: '나', youL: '터미널 명령', ccL: '플러그인: 훅, 스킬',
      agents: 'Codex 등', agentsL: 'AGENTS.md를 읽음', person: '나만 가능', personL1: '터미널 / passkey', personL2: '설정: passkey', personL3: 'Git: 터미널',
      core: 'core/ — 핵심', g1: '작업 공간', g1d: '설정은 제안을 통해서만 바뀜',
      g2: '작업과 인수', g2d: '증거는 상태에 묶임',
      g3: '작업 실행', g3d: '역할 + 실행자, 풀, 질문, 상황판',
      g4: '지식과 Git', g4d: '프로젝트 지도, 출처, 병합과 푸시',
      files: '파일 위치', spaceL: '작업 공간 · Obsidian · 자체 Git 기록',
      copy: '작업 복사본', copyL: 'git worktree · 브랜치 borshkit/<id>', project: '프로젝트', projectL: '내 파일과 Git 기록',
      exec: '실행자: 작업 묶음을 받고 스키마대로 JSON으로 답함', api: '모든 API · Ollama', own: '자체 프로그램',
      sub2: '구독으로', sub3: '키는 이름으로만', sub4: 'stdin을 읽음',
      aPacket: '작업 묶음', aJson: 'JSON 답', aWrite: '복사본에만 씀', aMerge: '병합', aPush: '푸시 →',
      caption: '결정과 기록은 핵심이 하고, 실행자는 제안만 합니다. 프로젝트에는 인수된 것만 들어갑니다.',
    },
    flow: {
      title: '작업 하나의 경로', sub: '모든 단계는 파일의 정확한 상태에 묶인 기록을 남깁니다',
      n1: '작업', n1c: 'task new', n1l: '목표 · 기준 · paths',
      n2: '분석', n2c: 'task check', n2l: '사각지대를 미리 표시',
      n3: '작업 실행', n3c: 'job run', n3l: '복사본의 implementer',
      n4a: '검사 (auto)', n4ac: 'task verify', n4al: '복사본에서 → 로그 + sha256',
      n4b: '리뷰 (model)', n4bc: '--role reviewer', n4bl: '다른 모델 계열',
      n5: '판정', n5c: 'task converge', n5l1: '상태', n5l2: '비교',
      lConverge: '결과 중 하나',
      o1: '수정 필요', o1l1: '검사나 리뷰의 FAIL', o1l2: '또는 paths 밖의 수정',
      o2: '검사 안 됨', o2l1: '증거가 없거나', o2l2: '만료됨',
      o3: '내 확인 대기', o3l1: '수동 기준, 또는 신뢰', o3l2: '목표가 없는 모델 PASS',
      o4: '인수됨', o4l1: '모든 목표 달성', o4l2: '이 상태에서',
      lFix: '수정', lRecheck: '다시 검사', lAnswer: '다시 판정',
      you: '나', youc: 'task confirm', youl: '인수 시트의 단계대로',
      m: '병합', mc: 'merge', ml1: '복사본이 깨끗', ml2: '하고 현재', ml3: 'main 포함',
      p: '푸시', pc: 'push', pl1: 'remote에', pl2: '새로 가는 것', pl3: '전부 키 검사',
      up: '작업 갱신', upc: 'task update', upl: 'main → 복사본, 다시 검사', lMoved: 'main이 앞서감',
      caption: '모델의 “완료”는 인수가 아닙니다. 검사, 다른 모델 계열의 리뷰, 그리고 내가 결정합니다.',
    },
    ev: {
      title: '증거는 상태에 묶입니다', sub: '상태는 지문 다섯 개; 모두 같으면 기록이 유효',
      state: '상태 (스냅숏)', r1: '프로젝트 파일', r1l: 'HEAD + 파일 sha256, 실행 비트, 서브모듈',
      r2: '계약', r2l: 'sha256(contract.json)', r3: '설정', r3l: 'sha256(settings/workspace.json)',
      r4: '자료', r4l: '작업이 저장한 출처의 sha256', r5: 'Borshkit 코드', r5l: 'sha256(core/*.mjs, bin/*.mjs)',
      src: '기록이 오는 곳', k1: '검사 (auto)', k1c: 'task verify', k1l: '검사 전후 스냅숏',
      k2: '리뷰 (model)', k2c: 'job run … reviewer', k2l: '리뷰어가 시작할 때의 스냅숏',
      k3: '나 (manual)', k3c: 'task confirm', k3l: '내가 답할 때의 스냅숏',
      rec: '기록', recl: '검사 로그는 자체 sha256으로 보호',
      cmp: '비교', cmpc: 'task converge', cmpq: '지금 스냅숏 = 기록의 state?', cmpl1: '예 → 기록 유효', cmpl2: '아니요 → 만료, 반영 안 됨',
      time: '시간에 따라 보면',
      lane1: '검사', e1: 'PASS', e2: '파일 수정', e3: '기록 만료', e4: '새 검사: PASS',
      lane2: '리뷰', f1: '리뷰어 시작', f2: '파일이 바뀜', f3: '답이 도착 — 바로 만료',
      caption: '1바이트, 계약, 설정, Borshkit 자체가 바뀌면 그 기록은 더 이상 인정되지 않습니다.',
    },
    pool: {
      title: '작업이 실행자를 찾는 방법', sub: '풀의 후보를 순서대로; 각 후보는 필터 네 개를 통과해야 함',
      job: '작업', jobc: 'job run', jobl: '풀은 순서 있는 목록',
      cand: '후보', gates: '필터 · 아니면 → 다음',
      g1: '개인정보 모드가 허용', g1l: '엄격 모드: local / no-train만',
      g2: '필요한 일을 할 수 있음', g2l: '역할 출력, 답 스키마, probe',
      g3: '작성자와 다른 계열', g3l: '리뷰용; 작성자는 authors.json',
      g4: '키·개인정보 없음', g4l: '발견 → 작업 전체 중단',
      run: '실행',
      runl1: '환경: 허용된 변수만',
      runl2: '쓰는 역할은 작업 복사본에서, 한 번에 하나',
      runl3: '묶음: 역할, 스킬, 계약, 검사',
      ok: '스키마대로 답함', okl1: '종료 0: 리뷰 → evidence,', okl2: '파일 → 복사본에 커밋',
      next: '한도', nextl1: '다음 후보로;', nextl2: '수정은 별도 커밋',
      fail: '다른 오류', faill1: '작업 FAILED;', faill2: '답은 나를 위해 보관',
      ask: '60초 넘게 무응답', askl1: '질문; 자동 조종은', askl2: '기다리거나 넘김',
      toNext: '다음 후보', exhausted: '후보가 남지 않음',
      stopT: '긴급 정지', stop: '풀 소진', stopl: '사람만 결정',
      stopf: '복원 지점 + 다음을 위한 맥락', you: '나', youc1: 'question answer <id> wait', youc2: 'job resume <job>',
      board: '상황판', s: ['claude: 한도 도달 → codex', 'codex: 작업 중…', 'codex: 완료 ✓ · 전환: 1회'],
      caption: '모든 넘김은 STATUS.md와 상태 표시줄에 나타나고, 사람은 정지했을 때만 결정합니다.',
    },
    kb: {
      title: '지식: 노트 → 그래프와 SQL → 맥락', sub: '진실의 원천은 노트; SQL은 파생물이라 다시 만들 수 있음',
      srcT: '출처', s1: 'JS/TS 코드', s1l: '→ imports, tests (+ 역방향)',
      s2: '프로젝트 Markdown', s2l: '→ documents, references',
      s3: 'Borshkit frontmatter', s3l: '→ 타입 있는 연결, DECLARED',
      s4: '내 노트', s4l: 'Borshkit은 읽기만 하고 바꾸지 않음',
      s5: '인수된 작업과 교훈', s5l: '교훈은 해당 코드와 함께 만료',
      build: '빌드', buildc: 'knowledge build', buildl: '같은 상태 → 같은 행',
      genl1: '코드와 문서에 대한 노트', genl2: '통째로 다시 씀',
      sqll: '노트에서 다시 만듦',
      useT: '쓰는 곳', u1: 'Obsidian', u1c: 'borshkit/을 볼트로', u1l: '[[링크]]로 그린 그래프',
      u2: '질의', u2c: 'knowledge sql "SELECT …"', u2l: 'SELECT / WITH만, 읽기 전용 DB',
      u3: '작업 맥락', u3c: 'knowledge context <task>', u3l: '작업 paths 기준 일부, ≤ 8000자',
      u4: '내보내기', u4c: 'knowledge export [--sql]', u4l: 'GitHub용 링크 또는 SQL 스크립트',
      example: '예시: 화살표는 연결을 담은 노트에서 시작',
      caption: '지도는 JS/TS와 Markdown을 읽습니다. Swift, Python, Go는 아직입니다. 인수는 지도를 쓰지 않습니다.',
    },
  },
  'zh-TW': {
    tagline: '任務 · 證據 · 驗收 · 知識',
    bannerDesc: '一碗冒著熱氣的羅宋湯，上方升起模組方塊：任務、檢查與知識匯聚於同一個工作區。',
    arch: {
      title: 'Borshkit 的結構', sub: 'Node.js 22+ · 零相依套件 · 一切存放在本機',
      inputs: '誰來呼叫', you: '你', youL: '終端機指令', ccL: '外掛：hooks、技能',
      agents: 'Codex 等', agentsL: '讀取 AGENTS.md', person: '只有你', personL1: '終端機 / passkey', personL2: '設定：passkey', personL3: 'Git：終端機',
      core: 'core/ — 核心', g1: '工作區', g1d: '設定只能透過提案變更',
      g2: '任務與驗收', g2d: '證據綁定到狀態',
      g3: '工作', g3d: '角色 + 執行者、池、提問、調度台',
      g4: '知識與 Git', g4d: '專案地圖、來源、合併與推送',
      files: '檔案位置', spaceL: '工作區 · Obsidian · 自己的 Git 歷史',
      copy: '任務副本', copyL: 'git worktree · 分支 borshkit/<id>', project: '專案', projectL: '你的檔案與 Git 歷史',
      exec: '執行者：收到任務包，依 schema 回覆 JSON', api: '任何 API · Ollama', own: '自己的程式',
      sub2: '透過訂閱', sub3: '金鑰只用名稱', sub4: '讀取 stdin',
      aPacket: '任務包', aJson: 'JSON 回覆', aWrite: '只寫入副本', aMerge: '合併', aPush: '推送 →',
      caption: '核心負責決定與記錄，執行者只提出建議。只有驗收過的內容會進入專案。',
    },
    flow: {
      title: '一個任務的路徑', sub: '每一步都留下記錄，並綁定到檔案的確切狀態',
      n1: '任務', n1c: 'task new', n1l: '目標 · 準則 · paths',
      n2: '分析', n2c: 'task check', n2l: '事先看到盲區',
      n3: '工作', n3c: 'job run', n3l: '副本中的 implementer',
      n4a: '檢查 (auto)', n4ac: 'task verify', n4al: '在副本中 → 記錄檔 + sha256',
      n4b: '審查 (model)', n4bc: '--role reviewer', n4bl: '不同的模型家族',
      n5: '結論', n5c: 'task converge', n5l1: '比對', n5l2: '狀態',
      lConverge: '結果之一',
      o1: '需要修正', o1l1: '檢查或審查的 FAIL', o1l2: '或在 paths 外修改',
      o2: '未檢查', o2l1: '沒有證據', o2l2: '或證據已過期',
      o3: '等你確認', o3l1: '手動準則，或沒有信任', o3l2: '目標的模型 PASS',
      o4: '已驗收', o4l1: '所有目標皆達成', o4l2: '在這個狀態下',
      lFix: '修正', lRecheck: '重新檢查', lAnswer: '重新結論',
      you: '你', youc: 'task confirm', youl: '依驗收清單的步驟',
      m: '合併', mc: 'merge', ml1: '副本乾淨', ml2: '且包含', ml3: '目前的 main',
      p: '推送', pc: 'push', pl1: '檢查所有', pl2: 'remote 沒有', pl3: '的內容',
      up: '更新任務', upc: 'task update', upl: 'main → 副本，重新檢查', lMoved: 'main 已前進',
      caption: '模型說「完成」不等於驗收：由檢查、另一個模型家族的審查和你來決定。',
    },
    ev: {
      title: '證據綁定到狀態', sub: '狀態是五個指紋；全部相符，記錄才有效',
      state: '狀態（快照）', r1: '專案檔案', r1l: 'HEAD + 檔案 sha256、執行位元、子模組',
      r2: '合約', r2l: 'sha256(contract.json)', r3: '設定', r3l: 'sha256(settings/workspace.json)',
      r4: '資料', r4l: '任務已存來源的 sha256', r5: 'Borshkit 程式碼', r5l: 'sha256(core/*.mjs, bin/*.mjs)',
      src: '記錄的來源', k1: '檢查 (auto)', k1c: 'task verify', k1l: '檢查前後的快照',
      k2: '審查 (model)', k2c: 'job run … reviewer', k2l: '審查者開始時的快照',
      k3: '你 (manual)', k3c: 'task confirm', k3l: '你回答時的快照',
      rec: '記錄', recl: '檢查記錄檔以自己的 sha256 保護',
      cmp: '比對', cmpc: 'task converge', cmpq: '目前快照 = 記錄的 state？', cmpl1: '是 → 記錄有效', cmpl2: '否 → 過期，不採計',
      time: '隨時間的變化',
      lane1: '檢查', e1: 'PASS', e2: '修改了檔案', e3: '記錄過期', e4: '新的檢查：PASS',
      lane2: '審查', f1: '審查者開始', f2: '檔案變更', f3: '回覆抵達 — 立刻過期',
      caption: '只要一個位元組、合約、設定或 Borshkit 本身改變，記錄就不再採計。',
    },
    pool: {
      title: '工作如何找到執行者', sub: '依序取池中的候選者；每個都要通過四道篩選',
      job: '工作', jobc: 'job run', jobl: '池是有順序的清單',
      cand: '候選者', gates: '篩選 · 否 → 下一個',
      g1: '隱私模式允許', g1l: '嚴格模式：只限 local / no-train',
      g2: '具備所需能力', g2l: '角色輸出、回覆 schema、probe',
      g3: '不是作者的家族', g3l: '用於審查；作者來自 authors.json',
      g4: '沒有金鑰和個資', g4l: '發現 → 整個工作停止',
      run: '執行',
      runl1: '環境：只有允許的變數',
      runl2: '寫入角色在任務副本中工作，一次一個',
      runl3: '任務包：角色、技能、合約、檢查',
      ok: '依 schema 回覆', okl1: '結束碼 0：審查 → evidence，', okl2: '檔案 → 副本中提交',
      next: '上限', nextl1: '交給下一個；', nextl2: '修改另成一個提交',
      fail: '其他錯誤', faill1: '工作 FAILED；', faill2: '回覆為你保留',
      ask: '超過 60 秒沒回應', askl1: '提問；自動駕駛', askl2: '等待或交出',
      toNext: '下一個候選者', exhausted: '沒有候選者了',
      stopT: '緊急停止', stop: '池已用盡', stopl: '只有人能決定',
      stopf: '還原點 + 給下一位的脈絡', you: '你', youc1: 'question answer <id> wait', youc2: 'job resume <job>',
      board: '調度台', s: ['claude：已達上限 → codex', 'codex：工作中…', 'codex：完成 ✓ · 切換：1 次'],
      caption: '每次交接都會顯示在 STATUS.md 和狀態列；只有停止時才由人決定。',
    },
    kb: {
      title: '知識：筆記 → 圖譜與 SQL → 脈絡', sub: '筆記是唯一真實來源；SQL 是衍生物，可以重建',
      srcT: '來源', s1: 'JS/TS 程式碼', s1l: '→ imports、tests（+ 反向）',
      s2: '專案的 Markdown', s2l: '→ documents、references',
      s3: 'Borshkit frontmatter', s3l: '→ 有型別的連結，DECLARED',
      s4: '你的筆記', s4l: 'Borshkit 只讀取，從不修改',
      s5: '已驗收的任務與教訓', s5l: '教訓會隨其程式碼一起過期',
      build: '建置', buildc: 'knowledge build', buildl: '同樣的狀態 → 同樣的資料列',
      genl1: '關於程式碼與文件的筆記', genl2: '整份重寫',
      sqll: '由筆記重建',
      useT: '誰在使用', u1: 'Obsidian', u1c: 'borshkit/ 當作 vault', u1l: '由 [[連結]] 畫出的圖譜',
      u2: '查詢', u2c: 'knowledge sql "SELECT …"', u2l: '只有 SELECT / WITH，唯讀資料庫',
      u3: '工作脈絡', u3c: 'knowledge context <task>', u3l: '依任務 paths 擷取，≤ 8000 字元',
      u4: '匯出', u4c: 'knowledge export [--sql]', u4l: 'GitHub 用的連結或 SQL 腳本',
      example: '範例：箭頭從記錄連結的那份筆記出發',
      caption: '地圖會讀 JS/TS 和 Markdown；Swift、Python、Go 尚未解析。驗收不使用地圖。',
    },
  },
  fr: {
    tagline: 'tâches · preuves · recette · connaissances',
    bannerDesc: 'Un bol de bortsch d’où montent de la vapeur et des cubes-modules : tâches, vérifications et connaissances réunies dans un même espace.',
    arch: {
      title: 'Comment Borshkit est construit', sub: 'Node.js 22+ · aucune dépendance · tout reste en local',
      inputs: 'Qui l’appelle', you: 'Toi', youL: 'commandes au terminal', ccL: 'plugin : hooks, skill',
      agents: 'Codex et autres', agentsL: 'lisent AGENTS.md', person: 'Toi seul', personL1: 'terminal / passkey', personL2: 'réglages : passkey', personL3: 'Git : terminal',
      core: 'core/ — le cœur', g1: 'Espace de travail', g1d: 'les réglages ne changent que par propositions',
      g2: 'Tâches et recette', g2d: 'les preuves sont liées à l’état',
      g3: 'Travaux', g3d: 'rôle + exécutant, pools, questions, tableau de bord',
      g4: 'Connaissances et Git', g4d: 'carte du projet, sources, fusion et envoi',
      files: 'Où sont les fichiers', spaceL: 'espace · coffre Obsidian · son propre Git',
      copy: 'Copie de la tâche', copyL: 'git worktree · branche borshkit/<id>', project: 'Projet', projectL: 'tes fichiers et ton historique Git',
      exec: 'Exécutants : reçoivent un paquet de tâche, répondent en JSON selon un schéma', api: 'Toute API · Ollama', own: 'Ton programme',
      sub2: 'par abonnement', sub3: 'clé par son nom', sub4: 'lit stdin',
      aPacket: 'paquet de tâche', aJson: 'réponse JSON', aWrite: 'écrivent dans la copie', aMerge: 'fusionner', aPush: 'pousser →',
      caption: 'Le cœur décide et enregistre ; les exécutants ne font que proposer. Seul le travail accepté arrive au projet.',
    },
    flow: {
      title: 'Le trajet d’une tâche', sub: 'chaque étape laisse une trace liée à l’état exact des fichiers',
      n1: 'Tâche', n1c: 'task new', n1l: 'objectif · critères · paths',
      n2: 'Analyse', n2c: 'task check', n2l: 'angles morts à l’avance',
      n3: 'Travail', n3c: 'job run', n3l: 'implementer dans la copie',
      n4a: 'Vérifications (auto)', n4ac: 'task verify', n4al: 'dans la copie → log + sha256',
      n4b: 'Revue (model)', n4bc: '--role reviewer', n4bl: 'une autre famille de modèles',
      n5: 'Verdict', n5c: 'task converge', n5l1: 'états', n5l2: 'comparés',
      lConverge: 'une des issues',
      o1: 'à corriger', o1l1: 'FAIL d’une vérif. ou revue', o1l2: 'ou retouche hors paths',
      o2: 'non vérifié', o2l1: 'pas de preuve', o2l2: 'ou elle est périmée',
      o3: 'attend ta recette', o3l1: 'critère manuel, ou PASS', o3l2: 'd’un modèle sans confiance',
      o4: 'accepté', o4l1: 'tous les objectifs', o4l2: 'atteints sur cet état',
      lFix: 'corriger', lRecheck: 'revérifier', lAnswer: 'nouveau verdict',
      you: 'Toi', youc: 'task confirm', youl: 'étapes de la feuille de recette',
      m: 'Fusionner', mc: 'merge', ml1: 'copie propre', ml2: 'qui contient', ml3: 'le main actuel',
      p: 'Pousser', pc: 'push', pl1: 'clés dans tout', pl2: 'ce qui est neuf', pl3: 'pour le remote',
      up: 'Mettre à jour la tâche', upc: 'task update', upl: 'main → dans la copie, revérifier', lMoved: 'main a avancé',
      caption: '« Terminé » selon le modèle n’est pas une recette : décident les vérifications, une revue d’une autre famille et toi.',
    },
    ev: {
      title: 'Une preuve est liée à un état', sub: 'un état, ce sont cinq empreintes ; si toutes concordent, la trace compte',
      state: 'État (instantané)', r1: 'Fichiers du projet', r1l: 'HEAD + sha256 des fichiers, bit x, sous-modules',
      r2: 'Contrat', r2l: 'sha256(contract.json)', r3: 'Réglages', r3l: 'sha256(settings/workspace.json)',
      r4: 'Matériaux', r4l: 'sha256 des sources gardées', r5: 'Code de Borshkit', r5l: 'sha256(core/*.mjs, bin/*.mjs)',
      src: 'D’où viennent les traces', k1: 'Vérification (auto)', k1c: 'task verify', k1l: 'instantané avant et après',
      k2: 'Revue (model)', k2c: 'job run … reviewer', k2l: 'instantané au départ du relecteur',
      k3: 'Toi (manual)', k3c: 'task confirm', k3l: 'instantané à ta réponse',
      rec: 'Trace', recl: 'le log est protégé par son propre sha256',
      cmp: 'Comparaison', cmpc: 'task converge', cmpq: 'instantané actuel = state de la trace ?', cmpl1: 'oui → la trace compte', cmpl2: 'non → périmée, non comptée',
      time: 'Ce que ça donne dans le temps',
      lane1: 'Vérification', e1: 'PASS', e2: 'un fichier modifié', e3: 'trace périmée', e4: 'nouvelle vérif. : PASS',
      lane2: 'Revue', f1: 'le relecteur part', f2: 'un fichier change', f3: 'la réponse arrive — périmée aussitôt',
      caption: 'Un octet, le contrat, les réglages ou Borshkit lui-même changent : la trace ne compte plus.',
    },
    pool: {
      title: 'Comment un travail trouve son exécutant', sub: 'candidats du pool dans l’ordre ; chacun passe quatre filtres',
      job: 'Travail', jobc: 'job run', jobl: 'un pool = liste ordonnée',
      cand: 'Candidats', gates: 'Filtres · non → suivant',
      g1: 'La confidentialité l’autorise', g1l: 'mode strict : local / no-train seulement',
      g2: 'Sait faire ce qu’il faut', g2l: 'sorties du rôle, schéma, probe',
      g3: 'Pas la famille de l’auteur', g3l: 'pour les revues ; auteurs : authors.json',
      g4: 'Ni clés ni données perso', g4l: 'trouvées → tout le travail s’arrête',
      run: 'Lancement',
      runl1: 'environnement : variables autorisées seulement',
      runl2: 'les rôles qui écrivent : dans la copie, un à la fois',
      runl3: 'paquet : rôle, skills, contrat, vérifications',
      ok: 'réponse au schéma', okl1: 'code 0 : revue → evidence,', okl2: 'fichiers → commit',
      next: 'limite', nextl1: 'au suivant ;', nextl2: 'retouches : leur commit',
      fail: 'autre erreur', faill1: 'travail FAILED ;', faill2: 'réponse gardée pour toi',
      ask: 'silence > 60 s', askl1: 'question ; le pilote', askl2: 'attend ou passe la main',
      toNext: 'candidat suivant', exhausted: 'plus de candidats',
      stopT: 'Arrêt critique', stop: 'Pool épuisé', stopl: 'seul un humain décide',
      stopf: 'point de retour + contexte pour la suite', you: 'Toi', youc1: 'question answer <id> wait', youc2: 'job resume <job>',
      board: 'tableau de bord', s: ['claude : limite atteinte → codex', 'codex : en cours…', 'codex : terminé ✓ · bascules : 1'],
      caption: 'Chaque passage de main apparaît dans STATUS.md et la ligne d’état ; un humain ne décide qu’à l’arrêt.',
    },
    kb: {
      title: 'Connaissances : notes → graphe et SQL → contexte', sub: 'les notes font foi ; le SQL en est dérivé et se reconstruit',
      srcT: 'Sources', s1: 'Code JS/TS', s1l: '→ imports, tests (+ sens inverse)',
      s2: 'Markdown du projet', s2l: '→ documents, references',
      s3: 'Frontmatter Borshkit', s3l: '→ liens typés, DECLARED',
      s4: 'Tes notes', s4l: 'Borshkit les lit, ne les modifie pas',
      s5: 'Tâches acceptées et leçons', s5l: 'une leçon périme avec son code',
      build: 'Construction', buildc: 'knowledge build', buildl: 'même état → mêmes lignes',
      genl1: 'notes sur le code et les docs', genl2: 'réécrites en entier',
      sqll: 'reconstruite depuis les notes',
      useT: 'Qui s’en sert', u1: 'Obsidian', u1c: 'borshkit/ comme coffre', u1l: 'graphe des [[liens]]',
      u2: 'Requêtes', u2c: 'knowledge sql "SELECT …"', u2l: 'SELECT / WITH, base en lecture seule',
      u3: 'Contexte d’un travail', u3c: 'knowledge context <task>', u3l: 'extrait selon paths, ≤ 8000 caractères',
      u4: 'Export', u4c: 'knowledge export [--sql]', u4l: 'liens pour GitHub ou script SQL',
      example: 'Exemple : une flèche part de la note qui contient le lien',
      caption: 'La carte lit JS/TS et Markdown ; Swift, Python et Go pas encore. La recette n’utilise pas la carte.',
    },
  },
};
